# Site settings
title: tddmonkeys ramblings
email: zodiaczx6@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 This is where I rant about software things and try to make the world a slightly better place
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://github.com/tddmonkey/tddmonkey.github.io"
twitter_username: tddmonkey
github_username:  tddmonkey

# Build settings
markdown: kramdown
